<div class="tab-custom" data-role="content" role="tabpanel" aria-hidden="false" style="display: block;">
    <h5>* You can add as many custom tabs as you need!</h5>
    <div class="table-bordered table-header-border overflow-y">
        <table>
            <thead>
                <tr>
                    <th>Size</th>
                    <th>Bust (cm)</th>
                    <th>Waist (cm)</th>
                    <th>Hip (cm)</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>XS</td>
                    <td>82,5</td>
                    <td>62</td>
                    <td>87,5</td>
                </tr>
                <tr>
                    <td>S</td>
                    <td>85</td>
                    <td>63,5</td>
                    <td>89</td>
                </tr>
                <tr>
                    <td>M</td>
                    <td>87,5</td>
                    <td>67,5</td>
                    <td>93</td>
                </tr>
                <tr>
                    <td>L</td>
                    <td>90</td>
                    <td>72,5</td>
                    <td>98</td>
                </tr>
                <tr>
                    <td>XL</td>
                    <td>93</td>
                    <td>77,5</td>
                    <td>103</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>