<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var \Magento\Catalog\Block\Product\ProductList\Toolbar $block
 * @var \Magento\Framework\Locale\LocaleFormatter $localeFormatter
 */
?>
<div class="field limiter">
        <div class="control">
            <select id="limiter" data-role="limiter" class="limiter-options">
                <?php foreach ($block->getAvailableLimit() as $_key => $_limit):?>
                    <option value="<?= $block->escapeHtmlAttr($_key) ?>"
                    <?php if ($block->isLimitCurrent($_key)):?>
                        selected="selected"
                        <?php endif ?>>
                        <span><?= $block->escapeHtml(__('Show')) ?></span>
                    <?= $block->escapeHtml(
                        is_numeric($_limit) ? $localeFormatter->formatNumber((int) $_limit) : $_limit
                    ) ?>
                    <?= $block->escapeHtml(__('per page')) ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
</div>
